@startuml ApplicationContext

note "v1.1 ApplicationContext" as Tip

interface BeanDefinitionRegistry {
  BeanDefinition getBeanDefinition();
  void registerBeanDefinition();
}

interface BeanFactory {
  Object getBean();
}

class DefaultBeanFactory {
}

interface ApplicationContext {
}

class ClassPathXmlApplicationContext {

}

BeanFactory <|-- ApplicationContext : extend
ApplicationContext <|..ClassPathXmlApplicationContext
BeanFactory <|.. DefaultBeanFactory
BeanDefinitionRegistry <|.. DefaultBeanFactory : implement

@enduml