@startuml ApplicationContext

note "v1.1 ApplicationContext" as Tip

interface BeanDefinitionRegistry {
  BeanDefinition getBeanDefinition();
  void registerBeanDefinition();
}

interface BeanFactory {
  Object getBean();
}

interface ApplicationContext extends BeanFactory {
}

class DefaultBeanFactory implements BeanFactory,BeanDefinitionRegistry {
}

class ClassPathXmlApplicationContext implements ApplicationContext {
}

@enduml