@startuml BeanFactory

note "v1.1 BeanDefinition Registry" as Tip

interface BeanDefinitionRegistry {
  BeanDefinition getBeanDefinition();
  void registerBeanDefinition();
}

interface BeanFactory {
  Object getBean();
}

class DefaultBeanFactory {
}

class XMLBeanDefinitionReader {
  BeanDefinitionRegistry registry;
}

BeanFactory <|.. DefaultBeanFactory : implement
BeanDefinitionRegistry <|.. DefaultBeanFactory 
XMLBeanDefinitionReader o-- BeanDefinitionRegistry : have >

@enduml